version: 2
jobs:
  lint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  build-and-test:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      # Ruby Gem Installs
      - restore_cache:
          key: gem-cache-{{ checksum "fastlane/Pluginfile" }}
      - run:
          name: Get Ruby Dependencies
          command: bundle install --path .bundle
      - save_cache:
          key: gem-cache-{{ checksum "fastlane/Pluginfile" }}
          paths:
            - .bundle
      # Pod Install
      - restore_cache:
          key: pod-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods Dependencies
          command: pod install
      - save_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
      # Test
      - run:
          name: Build and Run Test Suite
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPad Air
      - store_test_results:
          path: output
      - store_artifacts:
          path: output
workflows:
  version: 2
  build:
    jobs:
      - lint:
      - build-and-test:
          requires:
            - lint
